name: clippy
on: push
env:
  JQ_LIB_DIR: $(eval which jq)
jobs:
  clippy_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          args: "--all-features"
          token: ${{ secrets.GITHUB_TOKEN }}
