name: test
on: pull_request

env:
  RUST_BACKTRACE: 1

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            # n.b. libjq is pinned at 1.6 for now, with 1.7 support planned for the future (ref: #37)
            apt-deps: libjq-dev=1.6-2.1ubuntu3 libonig-dev
            jq-lib-dir: /usr/lib/x86_64-linux-gnu/
            onig-lib-dir: /usr/lib/x86_64-linux-gnu/
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2
      # XXX: libjq _appears to be_ already installed (and available via pkg-config?) on darwin.
      - name: Install System Deps (Linux)
        if: ${{ matrix.apt-deps }}
        run: sudo apt install -y ${{ matrix.apt-deps }}

      - name: Build workspace
        run: JQ_LIB_DIR="${{ matrix.jq-lib-dir }}" ONIG_LIB_DIR="${{ matrix.onig-lib-dir }}" cargo build

      - name: Test workspace
        run: JQ_LIB_DIR="${{ matrix.jq-lib-dir }}" ONIG_LIB_DIR="${{ matrix.onig-lib-dir }}" cargo test
