name: test
on: push
env:
  RUST_BACKTRACE: 1

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            # n.b. libjq is pinned at 1.6 for now, with 1.7 support planned for the future (ref: #37)
            apt-deps: libjq-dev=1.6-2.1ubuntu3 libonig-dev
            jq-lib-dir: /usr/lib/x86_64-linux-gnu/
            onig-lib-dir: /usr/lib/x86_64-linux-gnu/
          - os: macos-latest
            use-install-jq-action: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          profile: minimal
      - uses: Swatinem/rust-cache@v2

      - name: Install System Deps (Linux)
        if: ${{ matrix.apt-deps }}
        run: sudo apt install -y ${{ matrix.apt-deps }}

      - name: Install jq (macOS)
        uses: dcarbone/install-jq-action@v1.0.1
        with:
          version: 1.6
        if: ${{ matrix.use-install-jq-action }}

      - name: Build workspace
        # FIXME: config for linking is a real mess - figure out something tidier now that both linux/macOS are green
        run: |
          [[ ! -z "${{ matrix.use-install-jq-action }}" ]] && export JQ_LIB_DIR="$(eval which jq)"
          [[ ! -z "${{ matrix.jq-lib-dir }}" ]] && export JQ_LIB_DIR="${{ matrix.jq-lib-dir }}"
          [[ ! -z "${{ matrix.onig-lib-dir }}" ]] && export ONIG_LIB_DIR="${{ matrix.onig-lib-dir }}"
          cargo build

      - name: Test workspace
        # FIXME: config for linking is a real mess - figure out something tidier now that both linux/macOS are green
        run: |
          [[ ! -z "${{ matrix.use-install-jq-action }}" ]] && export JQ_LIB_DIR="$(eval which jq)"
          [[ ! -z "${{ matrix.jq-lib-dir }}" ]] && export JQ_LIB_DIR="${{ matrix.jq-lib-dir }}"
          [[ ! -z "${{ matrix.onig-lib-dir }}" ]] && export ONIG_LIB_DIR="${{ matrix.onig-lib-dir }}"
          cargo test
